/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as StudentRegistrationRouteImport } from './routes/student-registration'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDisbursementsRouteImport } from './routes/_authenticated/disbursements'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedLendersRouteImport } from './routes/_authenticated/lenders'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedCasesCaseIdRouteImport } from './routes/_authenticated/cases.$caseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRegistrationRoute = StudentRegistrationRouteImport.update({
  id: '/student-registration',
  path: '/student-registration',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDisbursementsRoute =
  AuthenticatedDisbursementsRouteImport.update({
    id: '/disbursements',
    path: '/disbursements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLendersRoute = AuthenticatedLendersRouteImport.update({
  id: '/lenders',
  path: '/lenders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCasesCaseIdRoute =
  AuthenticatedCasesCaseIdRouteImport.update({
    id: '/cases/$caseId',
    path: '/cases/$caseId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/student-registration': typeof StudentRegistrationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/disbursements': typeof AuthenticatedDisbursementsRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/lenders': typeof AuthenticatedLendersRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/cases/$caseId': typeof AuthenticatedCasesCaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/student-registration': typeof StudentRegistrationRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/disbursements': typeof AuthenticatedDisbursementsRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/lenders': typeof AuthenticatedLendersRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/cases/$caseId': typeof AuthenticatedCasesCaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/student-registration': typeof StudentRegistrationRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/disbursements': typeof AuthenticatedDisbursementsRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/lenders': typeof AuthenticatedLendersRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/cases/$caseId': typeof AuthenticatedCasesCaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/student-registration'
    | '/dashboard'
    | '/disbursements'
    | '/leads'
    | '/lenders'
    | '/reports'
    | '/cases/$caseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/student-registration'
    | '/dashboard'
    | '/disbursements'
    | '/leads'
    | '/lenders'
    | '/reports'
    | '/cases/$caseId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/student-registration'
    | '/_authenticated/dashboard'
    | '/_authenticated/disbursements'
    | '/_authenticated/leads'
    | '/_authenticated/lenders'
    | '/_authenticated/reports'
    | '/_authenticated/cases/$caseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  StudentRegistrationRoute: typeof StudentRegistrationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-registration': {
      id: '/student-registration'
      path: '/student-registration'
      fullPath: '/student-registration'
      preLoaderRoute: typeof StudentRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/disbursements': {
      id: '/_authenticated/disbursements'
      path: '/disbursements'
      fullPath: '/disbursements'
      preLoaderRoute: typeof AuthenticatedDisbursementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lenders': {
      id: '/_authenticated/lenders'
      path: '/lenders'
      fullPath: '/lenders'
      preLoaderRoute: typeof AuthenticatedLendersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cases/$caseId': {
      id: '/_authenticated/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof AuthenticatedCasesCaseIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDisbursementsRoute: typeof AuthenticatedDisbursementsRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedLendersRoute: typeof AuthenticatedLendersRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedCasesCaseIdRoute: typeof AuthenticatedCasesCaseIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDisbursementsRoute: AuthenticatedDisbursementsRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedLendersRoute: AuthenticatedLendersRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedCasesCaseIdRoute: AuthenticatedCasesCaseIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  StudentRegistrationRoute: StudentRegistrationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
